<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>KiriyamaServer.Worker</RootNamespace>
        <AssemblyName>KiriyamaServer.Worker</AssemblyName>
        <IsPackable>false</IsPackable>
        <UserSecretsId>Genocs</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <DockerfileContext>..\..</DockerfileContext>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.2" />
        <PackageReference Include="Microsoft.ApplicationInsights.Kubernetes" Version="8.0.1" />
        <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
        <PackageReference Include="Microsoft.Azure.ServiceBus" Version="5.2.0" />
        <PackageReference Include="Microsoft.Azure.Services.AppAuthentication" Version="1.6.2" />
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="10.0.2" />
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
        <PackageReference Include="Microsoft.VisualStudio.Azure.Kubernetes.Tools.Targets" Version="1.1.0" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Genocs.Logging" Version="9.0.0" />
        <PackageReference Include="Genocs.Telemetry" Version="9.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
    </ItemGroup>


</Project>
